name: Génération automatique du fichier files.js

on:
  push:
    paths:
      - 'rive/**'   
  workflow_dispatch: 

jobs:
  generate-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Installer Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20  

    - name: Installer les dépendances
      run: npm install

    - name: Générer files.js
      run: node generate-files.js

    - name: Commit et push des changements
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add files.js
        git commit -m "Mise à jour automatique de files.js"
        git push
