name: Génération automatique du fichier files.js

permissions:
  contents: write

on:
  push:
    paths:
      - 'rive/**'   # Déclenche seulement si quelque chose change dans /rive
  workflow_dispatch: # Permet de lancer manuellement aussi si besoin

jobs:
  generate-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Installer Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20  # ou une autre version stable

    - name: Installer les dépendances
      run: npm install

    - name: Générer files.js
      run: node generate-files.js

    - name: Check if there are changes
      run: |
        if git diff --cached --quiet; then
          echo "No changes to commit."
          exit 0
        fi    

    - name: Commit changes
      run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Update files.js automatically"
          git push
      
